### ISSUE TITLE
I want to know how to compress etc1 rgba. 

### ISSUE THREAD

**Issue by QinGeneral** [wolfpld/etcpak#2]
I want to know how to compress etc1 rgba. The usage is not mention etc1.

And I got a problem when compress .jpg file, output is "libpng error: Read Error". Maybe etcpak not work on .jpg file?

**Comment by wolfpld** [comment]
ETC1 does not support RGBA.
Use png as input image format.

**Comment by QinGeneral** [comment]
ok, I got it. Thanks.

**Comment by QinGeneral** [comment]
@wolfpld "ETC1 does not support RGBA", Dose it mean ETC1 RGBA == ETC1 Alpha, and etcpak not support etc1 alpha?
