### ISSUE TITLE
Merge quicketc2 

### ISSUE THREAD

**Issue by fire** [wolfpld/etcpak#6]
Is there a reason why quicketc2 patch isn't merged?

I rebased off https://github.com/fire/etcpak/tree/QuickETC2, but wanted to hear a review.

**Comment by wolfpld** [comment]
The quicketc2 branch is not ready to be merged as-is. It is currently being integrated part-by-part, but this is taking some time, as it's not a top priority.

**Comment by fire** [comment]
etcpak is great. Integrate quicketc2 as you're able.
